---
baseurl: "http://localhost"
languageCode: "en-us"
title: "Bits & Pixels"
Taxonomies:
    tag: "tags"
params:
    GoogleAnalyticsId: "UA-XYSYXYSY-X1111"
    FullName: "Matt Carrier"
    AvatarImage: "images/avatar.jpg"
    BannerImage: "http://placehold.it/500x300"
    Github: "https://github.com/icecreammatt"
    Twitter: "https://twitter.com/icecreammatt"
    Stackoverflow: "http://stackoverflow.com/users/873559/matt-carrier"
    Linkedin: "http://www.linkedin.com/in/carriermatt"
    GooglePlus: ""
    Facebook: ""
    Resume: "/resume"
    About: "I am a pixel connoisseur who enjoys the finer details of a Bresenham line. When not staring at arrays of smoothly rendered pixels I enjoy playingguitar and consuming coffee."
    SiteTitle: "mattcarrier.com"
---
